
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: SemVer release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions

      - uses: actions/setup-java@v2
        name: Setup JDK
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: SemVer release
        uses: cocogitto/cocogitto-action@v2
        with:
          check-latest-tag-only: true
          release: true
          git-user: 'github-actions'
          git-user-email: 'github-actions@github.com'

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}